steps:
  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/$TRIGGER_NAME:$COMMIT_SHA', '.']

  # Step 2: Push the Docker image to Google Container Registry (GCR)
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/$TRIGGER_NAME:$COMMIT_SHA']

  # Step 3: Deploy the Docker image to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'  # Use bash as the entrypoint
    args:
      - '-c'  # Run the following command in bash
      - |
        gcloud run deploy jira-data-center \
          --image=gcr.io/$PROJECT_ID/$TRIGGER_NAME:$COMMIT_SHA \
          --platform=managed \
          --region=$REGION \
          --allow-unauthenticated \
          --set-secrets=_DB_USERNAME_SECRET="$(_DB_USERNAME_SECRET)" \
          --set-secrets=_DB_PASSWORD_SECRET="$(_DB_PASSWORD_SECRET)" \
          --set-secrets=_JDBC_URL_SECRET="$(_JDBC_URL_SECRET)"

# Substitution variables for secrets and other values
substitutions:
  _DB_USERNAME_SECRET: 'projects/$PROJECT_ID/secrets/db-username/versions/latest'
  _DB_PASSWORD_SECRET: 'projects/$PROJECT_ID/secrets/db-password/versions/latest'
  _JDBC_URL_SECRET: 'projects/$PROJECT_ID/secrets/jdbc-url/versions/latest'

# Cloud Build timeout (optional)
timeout: '1800s'  # Set to a value that accommodates the build and deployment time.

# Cloud Build tags (optional)
tags:
  - 'jira'
