steps:
  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$_PROJECT_ID/jira-data-center', '.']

  # Step 2: Push the Docker image to Google Container Registry (GCR)
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$_PROJECT_ID/jira-data-center']

  # Step 3: Deploy the Docker image to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'jira-data-center'
      - '--image=gcr.io/$_PROJECT_ID/jira-data-center'
      - '--platform=managed'
      - '--region=us-central1'  # Change to your desired region
      - '--allow-unauthenticated'  # Remove this if you want to require authentication

# Cloud Build timeout (optional)
timeout: '1800s'  # Set to a value that accommodates the build and deployment time.

# Cloud Build tags (optional)
tags:
  - 'jira'
