steps:
  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - build
      - '--no-cache'
      - '-t'
      - >-
        $_AR_HOSTNAME/$PROJECT_ID/cloud-run-source-deploy/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA
      - .
      - '-f'
      - Dockerfile
    id: Build

  # Step 2: Push the Docker image to Google Container Registry (GCR)
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - push
      - >-
        $_AR_HOSTNAME/$PROJECT_ID/cloud-run-source-deploy/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA
    id: Push

  # Step 3: Deploy the Docker image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    args:
      - run
      - services
      - update
      - $_SERVICE_NAME
      - '--platform=managed'
      - >-
        --image=$_AR_HOSTNAME/$PROJECT_ID/cloud-run-source-deploy/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA
      - >-
        --labels=managed-by=gcp-cloud-build-deploy-cloud-run,commit-sha=$COMMIT_SHA,gcb-build-id=$BUILD_ID,gcb-trigger-id=$_TRIGGER_ID
      - '--region=$_DEPLOY_REGION'
      - '--quiet'
      # Cloud Build substitutions
      - '--set-env-vars=DB_USERNAME=$_DB_USERNAME'  # Replace with your database username
      - '--set-env-vars=DB_PASSWORD=$_DB_PASSWORD'  # Replace with your database password
      - '--set-env-vars=JDBC_URL=$_JDBC_URL'        # Replace with your JDBC URL
      - '--set-substitutions=_DB_USERNAME=$_DB_USERNAME,_DB_PASSWORD=$_DB_PASSWORD,_JDBC_URL=$_JDBC_URL,_JIRA_HOME_BUCKET=$_JIRA_HOME_BUCKET'

    id: Deploy
    entrypoint: gcloud

# Define the Dockerfile for building the image
images:
  - >-
    $_AR_HOSTNAME/$PROJECT_ID/cloud-run-source-deploy/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA
options:
  substitutionOption: ALLOW_LOOSE
substitutions:
  _AR_HOSTNAME: us-central1-docker.pkg.dev
  _PLATFORM: managed
  _TRIGGER_ID: 5424b461-8603-43a6-8f7d-4005e269a8b9
  _SERVICE_NAME: jira-cloud-run
  _DEPLOY_REGION: us-central1
  # Add database and bucket substitution values here
  _DB_USERNAME: your-database-username
  _DB_PASSWORD: your-database-password
  _JDBC_URL: your-jdbc-url
  _JIRA_HOME_BUCKET: your-jira-home-bucket
tags:
  - gcp-cloud-build-deploy-cloud-run
  - gcp-cloud-build-deploy-cloud-run-managed
  - jira-cloud-run
