# Cloud Build configuration to build and push the Jira Docker image to Artifact Registry

steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [
    'build',
    '-t',
    '${_GCP_REGION}-docker.pkg.dev/$PROJECT_ID/${_ARTIFACT_REGISTRY_REPO}/${_IMAGE_NAME}:${_IMAGE_TAG}',
    '.'  # Assumes Dockerfile and startup_scripts/ are in the current directory
  ]
  id: 'Build Jira Docker Image'

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', '${_GCP_REGION}-docker.pkg.dev/$PROJECT_ID/${_ARTIFACT_REGISTRY_REPO}/${_IMAGE_NAME}:${_IMAGE_TAG}']
  id: 'Push Jira Image to Artifact Registry'

# List of images built by this build
images:
- '${_GCP_REGION}-docker.pkg.dev/$PROJECT_ID/${_ARTIFACT_REGISTRY_REPO}/${_IMAGE_NAME}:${_IMAGE_TAG}'

# Default substitution variables. These can be overridden at build trigger time.
substitutions:
  _GCP_REGION: 'us-central1'               # Example: us-central1, europe-west1
  _ARTIFACT_REGISTRY_REPO: 'jira-repo'     # Your Artifact Registry repository name
  _IMAGE_NAME: 'jira-cloudrun-mysql'       # The name of the image
  _IMAGE_TAG: 'latest'                     # The tag for the image

# Optional: Configure build logging behavior
options:
  logging: CLOUD_LOGGING_ONLY
  # machineType: 'N1_HIGHCPU_8' # Optional: specify a larger machine type if needed for build
```
